version: '3.8'

services:
  cartame-bot:
    build:
      context: .
      network: host
    container_name: cartame_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - cartame-network

networks:
  cartame-network:
    driver: bridge
